adapter-hub/adapters

- src/transformers/adapter_training.py
> Fix loading prediction heads of task adapters

- adapter_docs/classes/weights_loaders.rst
- adapter_docs/contributing.md
- adapter_docs/index.rst
- adapter_docs/loading.md
- adapter_docs/quickstart.md
- adapter_docs/training.md
- src/transformers/__init__.py
... and some other minor updates to adapter docs.
Closes #43.
Note that the example code in the documentation requires #36 & #44 to be merged.
> Updated docs for adapter quickstart & adapter training

- src/transformers/adapter_bert.py
> Fix leave_out adapter config attribute

- examples/question-answering/run_squad.py
> Fix adapter args parsing and adapter saving

- src/transformers/trainer.py
> Fix Trainer for parallel setup

- adapter_docs/training.md
- examples/test_examples.py
- examples/text-classification/run_fusion_glue.py
- src/transformers/adapter_bert.py
- src/transformers/adapter_config.py
- src/transformers/adapter_model_mixin.py
- src/transformers/adapter_modeling.py
- src/transformers/adapter_utils.py
- tests/test_adapter_training.py
- fix parsing of adapter setup in flatten_adapter_names
- fix incorrect adapter loading in example script
- clearify on Fusion training in docs
- add tests for correct freezing when training adapters & fusion
Addressing multiple issues raised in #56.
> Minor fixes to Fusion code, examples, tests & docs

- src/transformers/adapter_bert.py
Head of model used to train https://adapterhub.ml/explore/qa/squad1/
> Flex head for SQuAD-style QA

- examples/test_adapter_examples.py
- examples/test_examples.py
- src/transformers/adapter_bert.py
- src/transformers/modeling_bert.py
- src/transformers/modeling_distilbert.py
- src/transformers/modeling_roberta.py
@hSterz Small changes to label input for our prediction heads to be in line with HF heads (as discussed). Additionally fixed the input to flex head models with multiple choice head. Also moved tests for adapter example scripts to a separate file.
> Adapt flex head model input to HF head model input

- src/transformers/adapters/model_mixin.py
- src/transformers/adapters/models/bart.py
- src/transformers/adapters/models/bert.py
- src/transformers/adapters/models/distilbert.py
- src/transformers/adapters/models/gpt2.py
> Add unfreeze_adapters param to train_fusion()

- examples/question-answering/run_qa.py
- examples/test_adapter_examples.py
> Change Fuse to Stack

- examples/language-modeling/run_clm.py
- examples/language-modeling/run_mlm.py
- examples/multiple-choice/run_swag.py
- examples/summarization/run_summarization.py
- examples/test_adapter_examples.py
- examples/text-classification/run_glue.py
- examples/text-classification/run_glue_alt.py
- examples/token-classification/run_ner.py
- examples/translation/run_translation.py
> Use adapter composition blocks in all example scripts

- src/transformers/adapters/model_mixin.py
- tests/test_adapter_fusion_common.py
> Add `with_head` parameter to save_adapter_fusion

- src/transformers/adapters/trainer.py
Hi,
I was experimenting with adapters and found a minor typo. Creating the PR for the same.
Thanks
> fix small typo

- src/transformers/adapters/layer.py
- src/transformers/adapters/model_mixin.py
- src/transformers/adapters/trainer.py
- tests/test_adapter_composition.py
- tests/test_adapter_training.py
> Acknowledge that "freezed" is not a thing

- src/transformers/adapters/composition.py
> Add XLM-Roberta to list of models supporting `Parallel`

- src/transformers/adapters/model_mixin.py
- tests_adapters/test_adapter_common.py
> Fix save_all_adapters such that with_head is not ignored

- src/transformers/adapters/model_mixin.py
- src/transformers/adapters/prefix_tuning.py
> Fix inferring batch size for prefix tuning

- src/transformers/adapters/configuration.py
- src/transformers/adapters/layer.py
- src/transformers/adapters/modeling.py
- src/transformers/adapters/training.py
Allows up-projection in adapter layer.
Closes #306.
> Support float reduction factors

- src/transformers/adapters/heads/language_modeling.py
- src/transformers/adapters/models/gpt2.py
- src/transformers/models/gpt2/modeling_gpt2.py
- src/transformers/models/t5/modeling_t5.py
- tests_adapters/methods/test_prefix_tuning.py
- tests_adapters/test_adapter_heads.py
> Fix generation with GPT-2, T5 and Prefix Tuning

- src/transformers/adapters/mixins/t5.py
- src/transformers/models/t5/modeling_t5.py
> Fix `T5EncoderModel` adapter integration

- src/transformers/models/deberta/modeling_deberta.py
> Fix Deberta self attention LoRA linear

- src/transformers/adapters/model_mixin.py
- tests_adapters/methods/test_compacter.py
This PR fixes with model classes not being able to access the shared parameters of compacter modules e.g. during sequence generation.
> Fix shared parameters module in model mixin

- examples/pytorch/dependency-parsing/utils_udp.py
- examples/pytorch/text-classification/run_glue.py
> Fix issues in GLUE and UDP example scripts

- src/transformers/adapters/trainer.py
- tests_adapters/test_adapter_trainer.py
If the `resume_from_checkoint`is wrongly indented which leads to errors as described in #506
> Fix resume_from_checkpoint

- src/transformers/adapters/lora.py
- src/transformers/models/gpt2/modeling_gpt2.py
Fixes #484. Explanation in https://github.com/adapter-hub/adapter-transformers/issues/484#issuecomment-1485542062.
> Restore compatibility in GPT-2 LoRALinear bias init

- notebooks/01_Adapter_Training.ipynb
- notebooks/03_Adapter_Fusion.ipynb
- notebooks/04_Cross_Lingual_Transfer.ipynb
- notebooks/05_Adapter_Drop_Training.ipynb
Fix notebook dataset column_rename() issue.
> Fix Notebook01 Dataset column_rename

- src/adapters/models/__init__.py
- src/adapters/models/t5/mixin_t5.py
Fixes https://www.notion.so/Fix-T5-f45601d8f58a49f3a2764d83a0ac645e?pvs=4
> Fix training T5 adapter models with Trainer

- src/adapters/heads/base.py
- src/adapters/model_mixin.py
- tests_adapters/test_adapter_heads.py
> Make sure output embeddings are frozen when training adapters

- README.md
- docs/adapter_composition.md
- docs/overview.md
Adding Prompt Tuning to all tables where it was missing and fixing broken links in the README.
> Adding Prompt Tuning to Missing Tables

- src/adapters/loading.py
This PR adds methods for loading from/ storing to state_dicts in AdapterLoader.
> Add loader methods for loading from/ to state_dict

- src/adapters/model_mixin.py
- tests/test_adapter_embeddings.py
Fixes a bug that was prevent embeddings from training properly and changes the test to catch that in the future.
> Fix embedding Training Bug

- docs/classes/models/encoderdecoder.rst
> Add __init__.py to encoder-decoder

- docs/loading.md
- notebooks/01_Adapter_Training.ipynb
- notebooks/03_Adapter_Fusion.ipynb
- notebooks/04_Cross_Lingual_Transfer.ipynb
- notebooks/Text_Generation_Training.ipynb
@calpt I added some changes to notebook 3 as requested, and made some various typo fixes inside other notebooks. A review for notebook 3 would be appreciated (i edited something on cell 6)! This is also my first pr on `adapters` :)
Also it looks like the notebook metadata changed as well even when I did a very minor edit to some text
> [DOCS] Fixed typos inside notebook files and doc pages

- .github/workflows/tests_torch.yml
- setup.py
> Upgrade Transformers to v4.44.x

- src/adapters/heads/model_mixin.py
- tests/test_adapter_heads.py
> Fix output_embeddings get/ set for empty active head

- setup.py
- src/adapters/models/albert/modeling_albert.py
- src/adapters/models/gptj/modeling_gptj.py
- src/adapters/models/mbart/modeling_mbart.py
- src/adapters/models/roberta/modeling_roberta.py
- src/adapters/models/xlm_roberta/modeling_xlm_roberta.py
Changes:
- add sdp attention to Roberta, Albert MBart, XLM-R
- re-copy GPT-J
> Upgrade Transformers to v4.45.x

- src/adapters/models/mistral/modeling_mistral.py
This pull request fixes flash attention forward method for mistral.
> fix flash attention for mistral. 
