src/transformers/adapter_bert.py, src/transformers/adapter_config.py, tests/test_adapter_fusion_loading.py
This PR includes two fixes:
- Adapter fusion layers do not require identical adapter configs anymore. However, to correctly add fusion layers, all fused adapters still have to define the same _locations_ for adapters (e.g. all should define either ``mh_adapter=True`` or ``mh_adapter=False``). Please check this @arueckle @JoPfeiff 
- Fixed a bug in the ``ModelAdaptersConfig.get()``
Added a test case covering the points mentioned.
=> Fix config retrieval for adapter fusion & bug in ModelAdaptersConfig

src/transformers/adapter_bert.py, src/transformers/adapter_model_mixin.py, src/transformers/adapter_utils.py, src/transformers/modeling_bert.py, src/transformers/modeling_roberta.py
- Adds a `set_active_adapters()` method to all model classes supporting adapters
- Automatically set active adapters in calls to `train_*()` methods, e.g. calling `model.train_adapter("mnli")` will also set the adapter "mnli" as default in every forward pass additionally to unfreezing it.
_Squash before merging!_
=> Add active_adapters to all model classes with adapters

adapter_docs/quickstart.md, adapter_docs/training.md, examples/README.md, examples/language-modeling/run_language_modeling.py, examples/multiple-choice/run_multiple_choice.py, examples/ner/.gitignore, examples/question-answering/run_squad.py, examples/test_examples.py, examples/text-classification/README.md, examples/text-classification/run_fusion_glue.py, examples/text-classification/run_glue.py, examples/text-classification/run_glue_alt.py, examples/token-classification/run_ner.py, src/transformers/__init__.py, src/transformers/adapter_config.py, src/transformers/adapter_training.py
Changes in this PR:
- Cleanup adapter setup in example scripts (e.g. switch to `set_active_adapters()`) & remove "magic" setup method
- Add CLI arguments for changing reduction factor & non-linearity in adapter config
- Add two small tests for example scripts using adapter training
- Mention adapter training in README example scripts (e.g. "The Big Table of Tasks")
- Minor improvements in docs (addressing https://github.com/Adapter-Hub/adapter-transformers/issues/26#issuecomment-677938162)
- Fixes #33. Supersedes #34.
=> Improvements for example scripts

src/transformers/adapter_config.py, tests/test_adapter_loading.py
#42 introduced a severe bug when saving & reloading a full model with adapters (ModelAdaptersConfig is not serialized/ deserialized correctly)
=> Hotfix for adapter config saving/loading

examples/benchmarking/plot_csv_file.py, src/transformers/adapter_bert.py, src/transformers/adapter_config.py, src/transformers/adapter_model_mixin.py, tests/test_save_id2label.py
The label information is now saved with the head. For a model with a specific head where the head config is None it is saved as an additional parameter. For a model with multiple heads it is a parameter in the ehad config, so every head can have different labels.
=> Label Information

src/transformers/pipelines.py
HF pipelines have a check for the type of the passed model. This excludes our ModelWithHeads classes at the moment.
This PR allows this:
```
model = BertModelWithHeads.from_pretrained("bert-base-uncased")
model.add_qa_head("qa")
pipeline = QuestionAnsweringPipeline(model=model, tokenizer=tokenizer)
```
=> Support XModelWithHeads in pipelines

src/transformers/adapter_bert.py, src/transformers/adapter_heads.py, src/transformers/adapter_model_mixin.py, src/transformers/configuration_utils.py, tests/test_adapter_common.py, tests/test_adapter_custom_head.py, tests/test_adapter_hub.py
Follow-up to #88. Closes #100.
Currently, the new prediction head modules (`PredictionHead` class) are not correctly registered as submodules of the model by PyTorch as they're not attributes of the model class (which is a PT module) but of the model config (which is not a PT module). This leads to multiple errors (e.g. not part of `state_dict`, ignored when setting train/ eval, moving to GPU (#100)).
Changed the implementation to put head modules into the `heads` module dict in the model class again. `config.prediction_heads` only holds references to the config dicts. Also removed some now unnecessary logic in `adapter_model_mixin.py`.
Added a check for this in prediction heads test cases: https://github.com/calpt/adapter-transformers/blob/3f6c40ca15926e7610aae1904f9b5792851e245d/tests/te …
=> Fix module registration of new prediction head modules

src/transformers/adapter_bert.py, src/transformers/adapter_distilbert.py, src/transformers/adapter_modeling.py, src/transformers/trainer.py, tests/test_adapter_training.py
This PR fixes the following for DistilBERT:
- AdapterFusion regularization by moving the fusion regularization loss implementation to the model classes
- the layer norm in the Transformer block: The layer norm module is part of the TransformerBlock class (different from BERT implementation), however we need to access it from the adapter module, which is a _submodule_ of the former. Therefore, we need some sort of reference in the submodule. The previous implementation didn't work as it copied the layer norm weights.
=> Hotfixes for DistilBERT adapter & AdapterFusion implementations

src/transformers/adapter_heads.py, src/transformers/modeling_bert.py, src/transformers/modeling_roberta.py
Follow-up of #101 (merge that first).
BERT & RoBERTa models have a pooler module built-in (used for HF prediction heads, but not flex heads). The output of the pooler is returned by the forward() call by default. As other models (e.g. DistilBERT) don't have this pooler, remove it from the input to the prediction head modules for consistent input handling and plug in back afterwards.
=>  Drop pooler output from flex head output for consistency between BERT & DistilBERT

notebooks/01_Adapter_Training.ipynb
Quick fix for the adapter training notebook by explicitly avoiding the label columns to be removed by the HF Trainer. Diff is pretty ugly, the only relevant changes is the last arg in:
```python
training_args = TrainingArguments(
learning_rate=1e-4,
num_train_epochs=6,
per_device_train_batch_size=32,
per_device_eval_batch_size=32,
logging_steps=200,
output_dir="./training_output",
overwrite_output_dir=True,
remove_unused_columns=False,
)
```
=> Fixed passing labels to model in adapter training notebook

src/transformers/adapter_heads.py, src/transformers/modeling_bert.py, src/transformers/modeling_roberta.py, tests/test_adapter_common.py
Make sure changes in 34a0ccacdac96d7ce4402b20da1fa6cd3ce99010 work for models with and without prediction heads.
Add prediction head labels to flex head tests.
=> Fix sequence tagging flex head output with given labels.

src/transformers/adapter_bert.py, src/transformers/adapter_distilbert.py, src/transformers/adapter_model_mixin.py, tests/test_adapter_fusion_common.py
Fix loading a full model with AdapterFusion (add a test case for this).
Pull _init_adapter_modules() to base mixin to remove redundancy for fusion/ adapter loading.
Add model-specific _add_adapter() method.
Change error for existing fusion config to warning to allow overriding identical fusion.
=> Fixes for (re-)loading models with AdapterFusion

src/transformers/adapter_bert.py, src/transformers/adapter_composition.py, src/transformers/adapter_distilbert.py, src/transformers/adapter_model_mixin.py, src/transformers/models/bert/modeling_bert.py, src/transformers/models/distilbert/modeling_distilbert.py, src/transformers/models/roberta/modeling_roberta.py, tests/test_adapter_composition.py
Follow-up to #116:
In the current parallel inference implementation, it is not possible to set an attention mask at the same time, making parallel inference difficult to use in practice. This PR adds a new hook (`adjust_attention_mask_for_parallel()`) called after every Transformers layer that ensures that the attention mask is properly resized when the hidden states are.
This is enough to make it work for BERT, RoBERTa & DistilBERT, but the Parallel block might not be usable for other model types (e.g. BART). Therefore, I added a whitelist for this block in `adapter_composition.py`.
=> Enable parallel adapter inference together with attention_mask

setup.py, src/transformers/trainer.py
Adding `--load_best_model_at_end` currently fails when added to a training script as it tries to load a full model.
=> Support loading adapters with load_best_model_at_end in Trainer

adding_adapters_to_a_model.md, src/transformers/adapter_model_mixin.py, src/transformers/models/bert/configuration_bert.py, src/transformers/models/distilbert/configuration_distilbert.py
Drafted a step-by-step guide on how adapters are added to model classes. This might be useful for us to follow when adding new models and it might also serve as a starting point for external contributors.
@hSterz Please check and comment how well this fits with GPT-2.
=> Add guide on how to add adapters to models

src/transformers/adapter_bart.py, src/transformers/adapter_bert.py, src/transformers/adapter_heads.py
Now, the prediction heads supported by a specific model are listed in the `head_types ` dictionary of the heads mixin. The model implementation don't have to implement `add_prediction_head_from_config()` anymore.
=> Flex head implementation refactorings

examples/seq2seq/run_summarization.py, examples/seq2seq/run_translation.py, src/transformers/__init__.py, src/transformers/utils/__init__.py
Implementation tested with https://github.com/Adapter-Hub/Hub/pull/24.
This PR also patches the new `check_min_version()` introduced by HF in all example scripts so that it doesn't use our version but the underlying HF version.
=> Add adapter support to seq2seq example scripts (translation & summarization)

src/transformers/adapters/layer.py, tests/test_adapter_fusion_common.py
Fixes a bug that caused fusion weights to be in training mode while the rest of the model is in eval mode when adding a new fusion block.
=> Ensure eval/ train mode is correct for AdapterFusion

src/transformers/adapters/model_mixin.py, src/transformers/trainer.py, tests/test_adapter_trainer.py
- Automatically switch to only saving adapters when model is freezed.
- Correctly restore active adapter setup when loading best full model at training end.
Fixes #166.
=> Fix & improve adapter saving/ loading using Trainer class

adapter_docs/v2_transition.md, src/transformers/adapters/layer.py, src/transformers/dependency_versions_table.py, src/transformers/modeling_utils.py, src/transformers/models/bart/modeling_bart.py, src/transformers/models/bert/modeling_bert.py, src/transformers/models/distilbert/modeling_distilbert.py, src/transformers/models/gpt2/modeling_gpt2.py, src/transformers/models/mbart/modeling_mbart.py, src/transformers/models/roberta/modeling_roberta.py, tests/test_adapter_common.py, utils/check_adapters.py
Fixes #165.
Re-adds the `adapter_names` argument to all `*ModelWithHeads` & `*Model` classes with adapter support.
=> Re-add adapter_names argument

setup.py, src/transformers/adapters/model_mixin.py, src/transformers/adapters/utils.py, src/transformers/dependency_versions_table.py
WIP for adding HuggingFace's model hub as a second source for loading adapters. Implementation via https://github.com/huggingface/huggingface_hub.
Adapter: https://huggingface.co/calpt/adapter-bert-base-squad1
```python
model = BertForSequenceClassification.from_pretrained("bert-base-uncased")
model.load_adapter("calpt/adapter-bert-base-squad1", source="hf")
```
```python
model = BertForSequenceClassification.from_pretrained("bert-base-uncased")
model.load_adapter("squad1", config="houlsby", source="ah")  # source="ah" is default & can be omitted
```
=> Add support for loading adapters from HuggingFace Model Hub

setup.cfg, src/transformers/adapters/head_utils.py, src/transformers/adapters/heads.py, src/transformers/adapters/loading.py, src/transformers/adapters/model_mixin.py, src/transformers/adapters/models/bert.py, src/transformers/models/bert/modeling_bert.py, src/transformers/models/roberta/modeling_roberta.py, tests/test_adapter_heads.py
Changes in detail:
- Enable conversion of static heads to flex head model heads.
- Add use_pooler argument classification & m.-choice heads.
- Allow passing of id2label to prediciton head loading.
- Save "num_labels" into static head config and use it for conversion to flex head
Current limitations:
`id2label`/`label2id` must be either present in the head config (often not the case, e.g. [here](https://adapterhub.ml/adapters/ukp/bert-base-uncased_lingaccept_cola_houlsby/)) or explicitly provided to `load_adapter()`/`load_head()`. Alternatively, `num_labels` can be passed to load_adapter(). Fix must be provided on the Hub side.
Example notebook: https://colab.research.google.com/drive/1JYAPKlPtJwCddc-Jra9WG9Cw5RVjFkhR?usp=sharing
=> Add automatic conversion of static heads when loaded via XModelWithHeads

src/transformers/adapters/model_mixin.py, src/transformers/models/bart/modeling_bart.py, src/transformers/models/bert/modeling_bert.py, src/transformers/models/distilbert/modeling_distilbert.py, src/transformers/models/gpt2/modeling_gpt2.py, src/transformers/models/mbart/modeling_mbart.py, src/transformers/models/roberta/modeling_roberta.py
=> Suppress no-adapter warning when adapter_names is given

adapter_docs/prediction_heads.md, adapter_docs/quickstart.md, src/transformers/adapters/configuration.py, src/transformers/adapters/heads.py, src/transformers/adapters/layer.py, src/transformers/adapters/model_mixin.py, src/transformers/adapters/models/bart.py, src/transformers/adapters/models/bert.py, src/transformers/adapters/models/distilbert.py, src/transformers/adapters/models/gpt2.py, tests/test_adapter_common.py, tests/test_adapter_fusion_common.py, tests/test_adapter_heads.py
- Adds methods for removing adapters (`delete_adapter()`), AdapterFusion (`delete_adapter_fusion()`) and prediction heads (`delete_head()`)
- Adds option `overwrite_ok` to `add_adapter()` to overwrite an existing adapter with the same name.
Resolves #179.
=> Add delete_adapter(), delete_adapter_fusion() and delete_head() methods

adapter_docs/classes/model_mixins.rst, adapter_docs/conf.py, adapter_docs/contributing.md, adapter_docs/huggingface_hub.md, adapter_docs/index.rst, adapter_docs/loading.md, src/transformers/adapters/hub_mixin.py, src/transformers/adapters/model_mixin.py
Follow-up to #162.
Similar to `push_to_hub()` in `transformers`, this PR adds a new method `push_adapter_to_hub()` that allows pushing a loaded adapter by name, e.g.:
```python
model.push_adapter_to_hub(
"my-awesome-adapter",  # repo name
"awesome_adapter",  # adapter name
adapterhub_tag="sentiment/imdb",
datasets_tag="imdb"
)
```
One of the two args `adapterhub_tag` and `datasets_tag` is required, so we can automatically pull adapters from huggingface.co to AdapterHub.ml with correct categorization.
Also added a new doc page (`adapter_docs/huggingface_hub.md`) for describing the HF Model Hub integration.
cc @osanseviero just fyi :)
=> Add method to push adapters to HF Model Hub

src/transformers/adapters/layer.py, src/transformers/adapters/models/bart.py, src/transformers/adapters/models/distilbert.py, src/transformers/adapters/models/gpt2.py
Change is required for T5 implementation in #182 to avoid name clashes.
=> Rename layer_norm -> transformer_layer_norm in adapter layer

src/transformers/adapters/heads.py, src/transformers/adapters/loading.py, src/transformers/adapters/model_mixin.py, tests/test_adapter_common.py, tests/test_adapter_fusion_common.py, tests/test_adapter_heads.py, tests/test_adapter_hub.py
There currently is a slightly unintuitive inconsistency in the library: when adding an adapter with `add_adapter()`/ `load_adapter()`, it is never activated, however (flex) heads (added either via `add_x_head()`/ `load_head()` or `load_adapter()`) are always activated.
This PR adds an additional `set_active` parameter to all adding/ loading method that allows direct activation of a loaded adapter/ fusion/ head. For compatibility, it is set to `False` by default for `add_adapter()`/`load_adapter()` and to `True` for `load_head()`.
=> Add `set_active` argument to add & load adapter/fusion/head methods

adapter_docs/prediction_heads.md
This PR fixes a small typo in the `prediction_heads.md`, replacing '_flexivle_' with '_flexible_'.
=> Fixing a typo in prediction_heads docs

src/transformers/adapters/configuration.py, src/transformers/adapters/layer.py, src/transformers/adapters/loading.py, src/transformers/adapters/model_mixin.py, src/transformers/adapters/modeling.py, src/transformers/trainer.py, tests/test_adapter_fusion_common.py, tests/test_adapter_trainer.py, tests/test_adapter_training.py
Move AF config to ModelAdaptersConfig. It's now possible to have multiple AF setups with different configs within one model.
Also removes `set_adapter_fusion_config()`.
=> Improve AdapterFusion config flexibility

src/transformers/adapters/models/bart.py, src/transformers/adapters/models/distilbert.py, src/transformers/adapters/models/gpt2.py
Fixes errors with torch DataParallel.
Closes #227.
=> Ensure reference from adapter layer to layer norm is always correct

adapter_docs/classes/adapter_layer.rst, src/transformers/__init__.py, src/transformers/adapters/composition.py, src/transformers/adapters/layer.py, src/transformers/adapters/model_mixin.py, src/transformers/adapters/models/bart.py, src/transformers/adapters/models/bert.py, src/transformers/adapters/models/distilbert.py, src/transformers/adapters/models/encoder_decoder.py, src/transformers/adapters/models/gpt2.py, src/transformers/adapters/models/t5.py, src/transformers/models/bart/modeling_bart.py, src/transformers/models/bert/modeling_bert.py, src/transformers/models/distilbert/modeling_distilbert.py, src/transformers/models/gpt2/modeling_gpt2.py, src/transformers/models/mbart/modeling_mbart.py, src/transformers/models/roberta/modeling_roberta.py, src/transformers/models/t5/modeling_t5.py, tests/test_adapter.py, tests/test_adapter_common.py, tests/test_adapter_fusion_common.py, tests/test_adapter_heads.py, tests/test_adapter_setup_context.py
**Note: Depends on #257**
---
Currently, we have a lot of redundant code in the model mixins of each model class integration (`src/transformers/adapters/models`).
This PR does a range of refactoring with the goal to unify and simplify adapter the adapter integrations into the currently supported models:
- `AdapterLayerBaseMixin` has been converted to a torch module, `AdapterLayer`, with a proper `forward()` method. This makes the integration into most models cleaner (except for (Ro)BERT(a)/ T5) as they don't require specific module mixins anymore
- The transformer now is expected to be passed to `AdapterLayer` instead of being a class attribute. This removes the need for a couple of model integration workarounds.
- A lot of management code (`train_adapter()`, `train_adapter_fusion()`, …
=> Unify & simplify model adapter integration

src/transformers/adapters/configuration.py, src/transformers/adapters/context.py, src/transformers/adapters/layer.py, src/transformers/adapters/model_mixin.py, src/transformers/models/bart/modeling_bart.py, src/transformers/models/bert/modeling_bert.py, src/transformers/models/distilbert/modeling_distilbert.py, src/transformers/models/encoder_decoder/modeling_encoder_decoder.py, src/transformers/models/gpt2/modeling_gpt2.py, src/transformers/models/mbart/modeling_mbart.py, src/transformers/models/roberta/modeling_roberta.py, src/transformers/models/t5/modeling_t5.py
Depends on #257, depends on #263
---
This PR adds a new `ForwardContext` class which provides a thread-local context to the forward pass of a model. This context can be used to store information relevant to the current forward pass without the need to add new parameters to the method definitions.
The context should be added to all adapter-supporting models by decorating the respective base model `forward()` methods with `@ForwardContext.wrap`.
This functionality is mainly for future use. Currently, it only replaces the `pre_transformer_forward()` method.
=> Add `ForwardContext` to wrap model forward pass

src/transformers/models/mbart/modeling_mbart.py
MBart places layer norms before FF/ attention blocks. Thus, they shouldn't be passed to adapter layers.
=> Fix MBart adapter implementation

src/transformers/adapters/trainer.py
Hi,
I just wanted to train my first language adapter with the `run_mlm.py` example script. I also used a validation corpus, but training does not start due to this error message:
```bash
Traceback (most recent call last):                                                                                                                                            
File "run_mlm.py", line 632, in <module>                                                                                                                                    
main()                                                                                                                                                                    
File "run_mlm.py", line 563, in main …
```
=> adapters-trainer: add missing preprocess_logits_for_metrics argument

.gitignore, src/transformers/adapters/loading.py, src/transformers/adapters/trainer.py, tests_adapters/test_adapter_trainer.py
=> [Trainer] Fix issue with AdapterFusion and `load_best_model_at_end`

examples/pytorch/README.md
Added `pytorch/` to the script links. It may have broken due to directory structure update.
=> Fix broken links

src/transformers/adapters/heads/base.py, src/transformers/adapters/trainer.py
Make sure `label_names` are set correctly in `AdapterTrainer` for model classes with flexible heads. Removes need for overriding `_remove_unused_columns()`.
=> Infer label names for training for flex head models

src/transformers/adapters/model_mixin.py, src/transformers/adapters/prefix_tuning.py, tests_adapters/methods/test_adapter_common.py, tests_adapters/test_adapter_composition.py
This PR introduces a new `adapter_summary()` method that provides a summary of the currently added adapters.
```python
model = AutoAdapterModel.from_pretrained("roberta-base")
for name, config in ADAPTER_CONFIG_MAP.items():
model.add_adapter(name, config=config)
print(model.adapter_summary())
```
outputs...
```
Name                     Architecture         #Param      %Param  Active   Train
--------------------------------------------------------------------------------
pfeiffer                 bottleneck           894528       0.718       0       1
houlsby                  bottleneck          1789056       1.435       0       1
pfeiffer+inv             bottleneck          1190592       0.955       0       1
houlsby+inv              bottleneck          2085120       1.673       0       1 …
```
=> Add `adapter_summary()` method

src/transformers/adapters/model_mixin.py
=> Ensure root dir exists when saving all adapters/heads/fusions.

src/transformers/adapters/heads/base.py, src/transformers/dependency_versions_table.py
=> Avoid attempting to set prediction head if non-existent

src/transformers/adapters/configuration.py, src/transformers/adapters/model_mixin.py, tests_adapters/methods/base.py, tests_adapters/methods/test_adapter_common.py, tests_adapters/methods/test_lora.py, tests_adapters/methods/test_prefix_tuning.py
This PR
- fixes an issue with loading adapters together with the full model weights using `from_pretrained()`
- fixes the tests for this use case
=> Fix loading adapters together with full model

src/transformers/adapters/prefix_tuning.py
The current way of initializing `input_tokens` in `__init__` and using `device = next(self.parameters()).device` to find device does not work for multi-gpu.
Instead we should use this [fix](https://github.com/huggingface/transformers/blob/1c220ced8ecc5f12bc979239aa648747411f9fc4/src/transformers/modeling_utils.py#L120) to find the device of the module and assign it to the input tokens.
=> multi-gpu support for prefix-tuning

src/transformers/adapters/mixins/bart.py, src/transformers/adapters/mixins/bert.py, src/transformers/adapters/mixins/distilbert.py, src/transformers/adapters/mixins/gpt2.py, src/transformers/adapters/mixins/t5.py, src/transformers/adapters/model_mixin.py, src/transformers/adapters/models/bart/adapter_model.py, src/transformers/adapters/models/bert/adapter_model.py, src/transformers/adapters/models/deberta/adapter_model.py, src/transformers/adapters/models/debertaV2/adapter_model.py, src/transformers/adapters/models/distilbert/adapter_model.py, src/transformers/adapters/models/gpt2/adapter_model.py, src/transformers/adapters/models/mbart/adapter_model.py, src/transformers/adapters/models/roberta/adapter_model.py, src/transformers/adapters/models/t5/adapter_model.py, src/transformers/models/bart/modeling_bart.py, src/transformers/models/bert/modeling_bert.py, src/transformers/models/deberta/modeling_deberta.py, src/transformers/models/deberta_v2/modeling_deberta_v2.py, src/transformers/models/distilbert/modeling_distilbert.py, src/transformers/models/gpt2/modeling_gpt2.py, src/transformers/models/mbart/modeling_mbart.py, src/transformers/models/roberta/modeling_roberta.py, src/transformers/models/t5/modeling_t5.py, tests_adapters/test_adapter_embeddings.py
- Introduces a new `EmbeddingAdaptersWrapperMixin` to make embedding methods available to heads model classes. This is implemented in new per-model heads mixins. Closes #382.
- Fixes size issues with embeddings. Closes #383.
- Detach embedding weights before cloning. Closes #384.
=> Fix issues with embedding training

src/transformers/adapters/wrappers/configuration.py, src/transformers/configuration_utils.py, src/transformers/models/encoder_decoder/configuration_encoder_decoder.py
=> Fix model serialization using `torch.save()` & `load()`

src/transformers/adapters/lora.py
This PR fixes to serious issues with recent implementations:
- Adding of LoRA weights to intermediate & output layer matrices. Closes #410.
- Invalid scaling of activations for intermediate & output layers in (IA)^3.
=> Fixes for LoRA & (IA)^3 on intermediate & output layers

adapter_docs/adapter_composition.md, src/transformers/adapters/context.py, src/transformers/adapters/layer.py, src/transformers/adapters/model_mixin.py, src/transformers/adapters/modeling.py, src/transformers/adapters/models/bart/adapter_model.py, src/transformers/adapters/models/bert/adapter_model.py, src/transformers/adapters/models/deberta/adapter_model.py, src/transformers/adapters/models/debertaV2/adapter_model.py, src/transformers/adapters/models/distilbert/adapter_model.py, src/transformers/adapters/models/gpt2/adapter_model.py, src/transformers/adapters/models/mbart/adapter_model.py, src/transformers/adapters/models/roberta/adapter_model.py, src/transformers/adapters/models/t5/adapter_model.py, src/transformers/adapters/models/vit/adapter_model.py, tests_adapters/test_adapter_fusion_common.py, tests_adapters/test_encoder_decoder.py
Example:
```python
model = AutoAdapterModel.from_pretrained("bert-base-uncased")
model.eval()
tokenizer = AutoTokenizer.from_pretrained("bert-base-uncased")
model.add_adapter("a")
model.add_adapter("b")
model.add_adapter_fusion(["a", "b"])
model.active_adapters = Fuse("a", "b")
input_data = tokenizer("this is great", return_tensors="pt")
output_1 = model(**input_data, output_adapter_fusion_attentions=True)
print(output_1.adapter_fusion_attentions)
```
=> Return AdapterFusion attentions using `output_adapter_fusion_attentions` argument

.github/workflows/close_stale_issues.yml, .github/workflows/stale.yml
Mark issues as stale after 90 days and close them after 14 days of further inactivity
=> Add GH action for stale issues bot

src/transformers/adapters/mixins/beit.py, src/transformers/models/beit/modeling_beit.py
This pull request fixes a bug in the BEiT adapter implementation, which I contributed in the first place. Although the tests were successful and the model converged on the test data set, during latest experimentation I became aware that the model in Adapter-Transformers, when it was *not* equipped with adapters, did output different embeddings than the original HF-Transformers model, which is obviously not intended. The bug fix contains two changes:
- Move the attention adapters call to the first residual connection, instead of calling it before lambda_1.
- Move the output adapters call into BeitLayer. In contrast to e.g. ViT it cannot be called in <Model>Output, due to the necessary lambda_2 and drop_path calls in BeitLayer before adapters need to be called.
This ensures that the model …
=> Fix bug in BEiT adapters

src/transformers/adapters/context.py, src/transformers/adapters/heads/base.py, src/transformers/adapters/model_mixin.py, src/transformers/adapters/models/bart/adapter_model.py, src/transformers/adapters/models/beit/adapter_model.py, src/transformers/adapters/models/bert/adapter_model.py, src/transformers/adapters/models/deberta/adapter_model.py, src/transformers/adapters/models/debertaV2/adapter_model.py, src/transformers/adapters/models/distilbert/adapter_model.py, src/transformers/adapters/models/gpt2/adapter_model.py, src/transformers/adapters/models/gptj/adapter_model.py, src/transformers/adapters/models/mbart/adapter_model.py, src/transformers/adapters/models/roberta/adapter_model.py, src/transformers/adapters/models/t5/adapter_model.py, src/transformers/adapters/models/vit/adapter_model.py, src/transformers/dependency_versions_table.py, src/transformers/generation_utils.py, tests_adapters/test_adapter_composition.py
Sequence generation using the `model.generate()` method currently doesn't support `Parallel` composition of adapters. This PR enables this, i.e. parallel sequence generation using different adapters using `Parallel` block for `AdapterModel` classes and adapters w. seq2seq heads.
Test: https://github.com/calpt/adapter-transformers/blob/827c627ddce5fcec1bef82e33721bcd12933fd51/tests_adapters/test_adapter_composition.py#L249-L274
=> Enable parallel sequence generation with adapters

src/transformers/adapters/layer.py, src/transformers/models/t5/modeling_t5.py
The adapter implementation of T5 currently passes the inputs to the adapter layer in the wrong order (i.e. residual inputs before hidden states). Thus, the sequential adapter implementation is effectively a parallel adapter.
This PR fixes the inputs order. It also clarifies the adapter layer input parameters.
=> Fix T5 adapter layer input

src/transformers/adapters/trainer.py, tests_adapters/test_adapter_trainer.py
Prevents an error when calling `Trainer.hyperparameter_search`, which requires that Trainer is initialized with `model` set to `None` and `model_init` is used instead. Resolved by using `self.model`, since `super().__init__` will set the value of `self.model` using `model_init`.
=> Fix adaptertrainer hyperparameter tuning

adapter_docs/index.rst, adapter_docs/method_combinations.md, adapter_docs/methods.md, adapter_docs/overview.md, src/transformers/adapters/configuration.py, src/transformers/adapters/model_mixin.py, src/transformers/adapters/utils.py, tests_adapters/test_adapter_config.py
This PR adds the possibility to use flexible adapter configuration strings which allow specifying custom config attributes.
Examples:
- Set config attributes: `model.add_adapter("name", config="parallel[reduction_factor=2]")`
- Config union `model.add_adapter("name", config="prefix_tuning|parallel")`
- more examples: https://github.com/calpt/adapter-transformers/blob/8df62b9de2a8ab51115b191aca35b2fb53c96539/tests_adapters/test_adapter_config.py#L95-L102
Documentation: https://github.com/calpt/adapter-transformers/blob/8df62b9de2a8ab51115b191aca35b2fb53c96539/adapter_docs/overview.md
Configuration strings can allow passing complex configurations e.g. via command line.
The adapter method documentation is now split into three pages:
- Overview and Configuration: introduction, table, …
=> Add adapter configuration strings & restructure adapter method docs

adapter_docs/classes/models/clip.rst, adapter_docs/index.rst, adapter_docs/model_overview.md, src/transformers/adapters/__init__.py, src/transformers/adapters/mixins/bart.py, src/transformers/adapters/mixins/clip.py, src/transformers/adapters/mixins/t5.py, src/transformers/adapters/model_mixin.py, src/transformers/adapters/prefix_tuning.py, src/transformers/adapters/wrappers/configuration.py, src/transformers/models/clip/configuration_clip.py, src/transformers/models/clip/modeling_clip.py, tests_adapters/methods/base.py, tests_adapters/methods/test_adapter_common.py, tests_adapters/test_adapter.py, tests_adapters/test_clip.py, utils/check_adapters.py
Closes #296. This PR includes the following changes:
- Integration of all adapter methods into `CLIPModel`, `CLIPTextModel` & `CLIPVisionModel` classes.
- Modify prefix tuning implementation to support different values for `n_heads` & `input_size` at different locations: This is required for CLIP text & vision encoder prefixes to be stored in the same PT pool.
- Introduction of `InvertibleAdaptersWrapperMixin` for model classes that support invertible adapters in a sub-module.
Install with:
```
pip install git+https://github.com/calpt/adapter-transformers.git@dev/clip
```
Tested the implementation for our current project.
=> Add adapter support to CLIP

src/transformers/adapters/trainer.py
When activating ```load_best_model_at_end```, AdapterTrainer first tries (unsuccessfully) to load the full model.
Moving the adapter loading code to ```_load_best_model()``` and thereby overwriting it should fix this.
=> Move loading best adapter to the trainer class

src/transformers/adapters/model_mixin.py, src/transformers/adapters/trainer.py, tests_adapters/test_adapter_trainer.py
=> Only compute fusion reg loss if fusion layer is trained

src/transformers/models/bart/modeling_bart.py, src/transformers/models/mbart/modeling_mbart.py, tests_adapters/methods/base.py, tests_adapters/methods/test_adapter_common.py, tests_adapters/methods/test_compacter.py, tests_adapters/methods/test_ia3.py, tests_adapters/methods/test_lora.py, tests_adapters/methods/test_prefix_tuning.py, tests_adapters/methods/test_unipelt.py, tests_adapters/test_adapter_heads.py
This PR fixes a critical issue in the LoRA & (IA)³ implementation of Bart & MBart, where LoRA & (IA)³ weights were not added to the intermediate and output linear layers of the model's decoder blocks.
I.e., adapter configs having `intermediate_lora=True` or `output_lora=True` are added incorrectly to (M)Bart models. For LoRA, this does not affect the default config, for (IA)³ it does (`intermediate_lora=True`).
To ensure correct addition of weights in the future, `get_adapter()` tests are updated to count the number of modules added per adapter.
=> Fix LoRA & (IA)³ implementation for Bart & MBart

adapter_docs/installation.md, adapter_docs/quickstart.md, adapter_docs/training.md
This PR updates the Chapter "Getting Started" for the adapter-docs. 
Contributions:
1. Mainly fixed some typos and inconsistencies
2. Updated the quickstart code demonstration
3. Fixed broken link, there I need your ok that this is a good alternative
=> Update doc chapter "Getting Started"

docs/classes/models/xmod.rst, docs/index.rst, docs/model_overview.md, src/adapters/__init__.py, src/adapters/composition.py, src/adapters/configuration/adapter_config.py, src/adapters/head_utils.py, src/adapters/layer.py, src/adapters/lora.py, src/adapters/modeling.py, src/adapters/models/__init__.py, src/adapters/models/auto/adapter_model.py, src/adapters/models/xmod/__init__.py, src/adapters/models/xmod/adapter_model.py, src/adapters/models/xmod/mixin_xmod.py, src/adapters/models/xmod/modeling_xmod.py, src/adapters/prefix_tuning.py, tests_adapters/models/test_xmod.py, tests_adapters/test_adapter_conversion.py, tests_adapters/test_xmod.py, utils/convert_xmod_checkpoint.py
Integrates adapter support into HuggingFace's X-MOD implementation.
- X-MOD paper: http://dx.doi.org/10.18653/v1/2022.naacl-main.255
- HF docs: https://huggingface.co/docs/transformers/model_doc/xmod
HF model already supports adapters integrated into X-MOD. Several changes were necessary to make HF's implementation compatible with Adapters:
- deactivate HF's custom adapter logic: `lang_ids` parameter and `set_default_language()` are deactivated in favor of regular adapter methods. Documented in model class docs.
- conversion of adapter checkpoints: `utils/convert_xmod_checkpoint.py` Only converted checkpoints can be used with Adapters. We'll convert & re-upload some of the original X-MOD checkpoints to the Hub.
=> Add adapter support for X-MOD model

docs/classes/models/electra.rst, docs/classes/models/llama.rst, docs/index.rst, docs/model_overview.md, src/adapters/__init__.py, src/adapters/composition.py, src/adapters/head_utils.py, src/adapters/models/__init__.py, src/adapters/models/auto/adapter_model.py, src/adapters/models/electra/__init__.py, src/adapters/models/electra/adapter_model.py, src/adapters/models/electra/modeling_electra.py, tests_adapters/models/test_electra.py, tests_adapters/test_electra.py
Adding support for the ElectraModel. Since the ElectraModel has several classes copied from the BertModel, the mixins from the BertModel are reused.
=> Electra Support

src/adapters/configuration/adapter_config.py, src/adapters/model_mixin.py, tests/methods/base.py, tests/methods/test_adapter_common.py, tests/methods/test_compacter.py, tests/methods/test_ia3.py, tests/methods/test_lora.py, tests/methods/test_prefix_tuning.py, tests/test_adapter.py, tests/test_albert.py
Changes multiple things related to `leave_out`:
- Add config attribute for LoRA & (IA)^3
- Fixes error when using `leave_out` with compacter.
- Adds a test case for all supporting adapter methods.
=> Add `leave_out` to LoRA / (IA)^3

README.md
Hi :)
this PR has  a minor fix for the installation (from source) section: the `git checkout` command is removed, because there's no longer a `adapters` branch here.
=> readme: minor fix for installation section

src/adapters/heads/base.py, src/adapters/models/bart/adapter_model.py
Fixes #494 and fixes #563.
`BartAdapterModel` currently tries to extract CLS token representations from EOS tokens independent from the used heads (if at all). This causes weird issues for models not using CLS token based heads.
This PR moves CLS token rep extraction into the specific head classes to only compute it when needed. Two (re-usable) new args to `forward_head()` are introduced:
- `get_cls_from_eos_tokens`: to indicate a model uses CLS reps from EOS tokens
- `eos_mask`: token mask to extract CLS reps (required when passing `get_cls_from_eos_tokens=True`)
=> [Bart] Move CLS rep extraction from EOS tokens to head classes

src/adapters/model_mixin.py
=> Remove faulty adapter skip check in InvertibleAdaptersMixin

src/adapters/heads/base.py, src/adapters/loading.py
This should fix an issue raised in #629.
=> Fix prediction head loading for T5

docs/overview.md
Exactly what the title says -- removed duplicated text from the overview page in the docs.
=> Fix obvious typo in docs

src/adapters/methods/adapter_layer_base.py, src/adapters/methods/bottleneck.py
Closes #650.
The current implementation of composition blocks via `composition_to_func_map` prevents usage with torch's DataParallel built into HF Trainer, as described in #649, #650.
This PR fixes compatibility with DataParallel. Tested with the script provided in #650 running on two GPUs.
=> Fix DataParallel training with adapters

src/adapters/configuration/adapter_config.py, src/adapters/methods/modeling.py
=> Add dropout to bottleneck adapters

src/adapters/methods/prefix_tuning.py, src/adapters/models/clip/modeling_clip.py, tests/methods/base.py, tests/methods/test_adapter_common.py, tests/methods/test_lora.py, tests/methods/test_prefix_tuning.py, tests/methods/test_prompt_tuning.py, tests/test_adapter.py, tests/test_clip.py
Fixes #559.
The Prefix Tuning implementation has issues with incompatible dtypes when switching away from the default float32. This PR fixes the issue caused by the prefix mask and adds test cases.
=> Fix fp16/ bf16 for Prefix Tuning

src/adapters/models/t5/modeling_t5.py
Fixes #669 
Changes in this PR:
- Avoid throwing `RuntimeError` due to dimension mismatch occuring when passing the positional encoding from layers dropped by AdapterDrop to layers modified by prefix tuning.
=> Fix Training Error with AdapterDrop and Prefix Tuning

src/adapters/utils.py
Fixes #570.
This applies for adapters loaded from the (now-legacy) AH repo, and if `TORCH_HOME` is not set.
=> Fix default cache path for adapters loaded from AH repo

src/adapters/methods/adapter_layer_base.py, src/adapters/methods/bottleneck.py, src/adapters/methods/lora.py
Fixes #664.
Changes in this PR:
- Avoid throwing `NotImplementedError` in an unsupported block if none if the child adapters are part of the respective layer.
- Pass along "last" invoked adapter module name in LoRA & bottleneck states to make sure "last" is actually existing in the respective layer.
=> Fix skipping composition blocks in not applicable layers

docs/method_combinations.md, src/adapters/configuration/adapter_config.py
=> Fix Unipelt Lora default config

src/adapters/utils.py
If `source` is not specified in `load_adapter()`, will switch priorities to first search on HF Hub and only on AH if not found there. Related to AH deprecation (#668).
This also fixes an bug with auto-resolving adapters for which no model index file is given in AH (e.g. currently for Llama-2).
=> Switch resolving order if source not specified in `load_adapter()`

docs/contributing/adding_adapters_to_a_model.md, src/adapters/model_mixin.py, src/adapters/models/albert/mixin_albert.py, src/adapters/models/bart/mixin_bart.py, src/adapters/models/beit/mixin_beit.py, src/adapters/models/bert/mixin_bert.py, src/adapters/models/clip/mixin_clip.py, src/adapters/models/deberta/mixin_deberta.py, src/adapters/models/deberta_v2/mixin_deberta_v2.py, src/adapters/models/distilbert/mixin_distilbert.py, src/adapters/models/gpt2/mixin_gpt2.py, src/adapters/models/gptj/mixin_gptj.py, src/adapters/models/llama/mixin_llama.py, src/adapters/models/t5/mixin_t5.py, src/adapters/models/vit/mixin_vit.py, src/adapters/utils.py
Adapters currently does not work correctly with passing `device_map="auto"` in a model's `from_pretrained()`. Device auto-mapping is handled by HF accelerate, which wraps the original module forward method.
This PR fixes compatibility of Adapters' post-hoc model wrapping with Accelerate's device auto-mapping via wrapping the forward pass.
Fixing this is required for enabling quantized training of adapters (bottleneck & prefix-tuning) in #663.
The fix can be tested like this:
```python
import adapters
from transformers import AutoTokenizer, AutoModelForSequenceClassification
model_name = "t5-small"
tokenizer = AutoTokenizer.from_pretrained(model_name)
model = AutoModelForSequenceClassification.from_pretrained(
model_name,
device_map="auto"
)
adapters.init(model) …
```
=> Fix compatibility of adapters with HF Accelerate auto device-mapping

src/adapters/utils.py
The config key on HF side has not changed from `adapter_transformers`. Thus, currently the model name is never returned correctly for HF adapters.
This is required to fix the HF hub inference widgets.
=> Fix reading model info in `get_adapter_info()` for HF

src/adapters/loading.py, src/adapters/model_mixin.py, src/adapters/utils.py, tests/test_adapter_safetensors.py
Resolves #661.
Methods for saving & loading adapters, prediction heads & adapter fusions get a new parameter `use_safetensors` to save & load via Safetensors.
=> Support saving & loading via Safetensors

notebooks/QLoRA_Llama_Finetuning.ipynb, src/adapters/methods/bottleneck.py, src/adapters/model_mixin.py, src/adapters/trainer.py
This PR:
- introduces new methods `adapter_to()` & `adapter_fusion_to()` to move only adapter weights to device or convert dtype
- avoids moving full model in `AdapterTrainer` when loading best model.
Fixes #694.
=> Add `adapter_to()` method for moving & converting adapter weights

docs/embeddings.md, notebooks/Adapter_With_Embeddings.ipynb
Improve Embedding Documentation (#643 ) by:
- Adding an example notebook
- Updating the embedding page in the documentation
=> Update Embedding Documentation

docs/loading.md, src/adapters/model_mixin.py, src/adapters/utils.py, tests/test_adapter_hub.py
This PR implements an automatic redirect for `load_adapter()` from Hub repo adapters to the HF Hub:
- If `source` is not specified, will automatically redirect attempts to load from Hub repo to HF Hub. Will also issue a warning to set new id explicitly.
- if `source="ah"` explicitly, will still load from Hub repo link and issue a warning.
Also updated docs accordingly & removed sections specific to Hub repo loading.
=> Add download redirect for AH adapters to HF

setup.py, src/adapters/methods/prefix_tuning.py, src/adapters/model_mixin.py, src/adapters/models/bert/modeling_bert.py, src/adapters/models/vit/modeling_vit.py, src/adapters/utils.py
Changes needed for sync:
- BERT/ ViT: Copy & adapt new sdpa attention classes
- Update copied `_prepare_encoder_decoder_kwargs_for_generation` in model mixin
- Adjust 2dim attention masks for prompt tuning
=> Upgrade Transformers to v4.41.x

src/adapters/models/llama/modeling_llama.py
=> Fix Llama sdpa/ flash attention + adapters

setup.py, src/adapters/head_utils.py, src/adapters/model_mixin.py, src/adapters/models/beit/modeling_beit.py, src/adapters/models/gpt2/modeling_gpt2.py, src/adapters/models/mistral/modeling_mistral.py
Changes needed for sync:
- remove setting `_hf_peft_config_loaded` for HF Trainer
- fix BEiT interpolate_pos_encoding
- add sdpa to GPT-2
- add LlamaForTokenClassification head conversion
=> Upgrade Transformers to v4.42.x

docs/classes/models/plbart.rst, docs/huggingface_hub.md, docs/index.rst, docs/loading.md, src/adapters/configuration/adapter_fusion_config.py, src/adapters/hub_mixin.py, src/adapters/loading.py, src/adapters/model_mixin.py, src/adapters/utils.py, tests/test_adapter_config.py
See https://github.com/adapter-hub/adapters/discussions/725, section on v1.0.0
=> Remove loading adapters from 'ah' & source parameter

.github/workflows/tests_torch.yml, setup.py, src/adapters/heads/model_mixin.py, src/adapters/models/beit/modeling_beit.py, src/adapters/models/clip/modeling_clip.py, src/adapters/models/llama/modeling_llama.py, tests/methods/base.py
Changes required for sync:
- re-copy Llama & Beit attention
- add clip sdp & flash attn
- fix tie_weights method
- upgrade torch version in tests
=> Upgrade Transformers to v4.43.x

src/adapters/methods/bottleneck.py, src/adapters/model_mixin.py, src/adapters/models/llama/modeling_llama.py, src/adapters/trainer.py, tests/test_adapter_trainer.py
Fixes in this PR:
- Fix 'NoneType' error if context not available
- Fix Llama grad checkpointing training.
- Add quantized training test.
Still existing limitation:
- ForwardContext does not work with gradient checkpointing, ie methods such as reft or prefix tuning don't work with gradient checkpointing currently.
=> Don't throw error if ForwardContext is not available

setup.py
Updated `sphinx-rtd-theme==2.0.0`.
The styling after building it with `make clean && make html` looked the same to me,
but maybe a reviewer could confirm this.
Updating this package fixes the search bar.
=> Fix search on docs.adapterhub.ml

examples/pytorch/language-modeling/run_clm.py, examples/pytorch/language-modeling/run_mlm.py, examples/pytorch/multiple-choice/run_swag.py, examples/pytorch/question-answering/run_qa.py, examples/pytorch/question-answering/run_seq2seq_qa.py, examples/pytorch/summarization/run_summarization.py, examples/pytorch/text-classification/run_glue.py, examples/pytorch/text-generation/run_generation.py, examples/pytorch/token-classification/run_ner.py, examples/pytorch/translation/run_translation.py, src/adapters/utils.py
This PR solves an import error, which causes Adapters to not work with huggingface_hub version >= 0.26. This import error comes from HuggingFace removing deprecated functions.
Additionally, I updated all our example notebooks because they were outdated and used the `use_auth_token` parameter that isn't used by Hugging Face anymore.
To download files from repositories, we have the `download_cached(...)` and `get_from_cache(...)` functions in src/adapters/utils.py. Hugging Face has used similar methods in the past, too - our get_from_cache is copied from them. Now, Hugging Face uses a new method: `hf_hub_download(...)` (huggingface_hub/file_download.py)
However, we can't use the new `hf_hub_download(...)` function because it has the validate_hf_hub_args decorator that checks if the …
=> Fix import error for Huggingface-hub version >=0.26.0 & Update Notebooks

src/adapters/models/bart/modeling_bart.py, src/adapters/models/distilbert/modeling_distilbert.py, src/adapters/models/llama/modeling_llama.py, src/adapters/models/mbart/modeling_mbart.py, src/adapters/models/mistral/modeling_mistral.py, src/adapters/models/mt5/modeling_mt5.py, src/adapters/models/plbart/modeling_plbart.py, src/adapters/models/t5/modeling_t5.py, tests/composition/test_parallel.py, tests/test_deberta.py, tests/test_gpt2.py, tests/test_whisper.py
Currently, many model implementation don't handle bsz replication caused by parallel composition correctly for attention matrix LoRAs. This PRs loosens bsz reshaping to enable this. Also adds a test case for LoRA parallel.
Resolves #744.
=> Fix LoRA parallel composition

notebooks/ViT_AdapterPlus_FineTuning.ipynb, src/adapters/methods/modeling.py
Fixes #745 
When "mam_adapter" is specified, the code will now look for the `nn.Linear` or `PHMLayer` inside the `self.down_adapter` layer sequence and apply the initialization on the correct layer
edit: also removes an extra block of code in the `AdapterPlus` notebook
=> [BUG] Fixes Bottleneck Configs to work with ln_before = True and init_weights = "mam_adapter"

src/adapters/configuration/adapter_config.py, src/adapters/methods/lora.py, src/adapters/methods/reft.py
Aims to fix https://github.com/adapter-hub/adapters/issues/766
Backwards compatible, since `dtype` defaults to `None` if not set in `AdapterConfig`.
=> Allow specifying adapter dtype in AdapterConfig

setup.py, src/adapters/__init__.py, src/adapters/loading.py, src/adapters/methods/lora.py
Resolves issue described in #760.
**IMPORTANT**: this fix restores weights compatibility with adapter-transformers. Compatibility to previous adapters versions is kept via a compat patch.
The current implementation of LoRA/ (IA)^3 in `adapters ` versions < 1.1.0 does not correctly implement adapter states scaling via the LoRA `alpha` attribute, effectively ignoring `alpha` and always applying a scaling of 1.0.
This PR restores the correct original behavior as found in adapter-transformers/ original LoRA implementation.
As this change breaks all adapters pre-trained using `adapters` versions 0.1.0 - 1.0.1, a backward compatibility patch is introduced that automatically sets `alpha = r` for LoRAs for adapters that were trained using affected versions. This ensures all previous adapters …
=> Fix default Lora/ (IA)^3 scaling in forward

docs/methods.md, notebooks/ViT_AdapterPlus_FineTuning.ipynb, src/adapters/configuration/adapter_config.py
This pr fixes the configuration parameters set in the `AdapterPlusConfig`
edit: This pr also incorporates some updates as described inside the comments in #764 
1) Added some more information regarding training configurations inside the `AdapterPlusConfig` and its corresponding notebook
2) Added more info regarding layer norms inside the documentation
=> [BUG] Fix `AdapterPlus` config

docs/adapter_composition.md, docs/loading.md, docs/quickstart.md, src/adapters/composition.py, src/adapters/hub_mixin.py, src/adapters/model_mixin.py, src/adapters/utils.py, tests/methods/test_adapter_common.py, tests/test_clip.py
Closes #441; closes #747.
This PR introduces a set of new methods for saving, loading and pushing entire adapter compositions with one command:
- `save_adapter_setup()`
- `load_adapter_setup()`
- `push_adapter_setup_to_hub()`
They require two main params:
- `adapter_setup`: the adapter composition to be saved. Identical to what can be specified for `active_adapters`
- `head_setup`: for models with heads, the head setup to save along with the adapters. Identical to what can be specified for `active_head`
Docs [here](https://github.com/adapter-hub/adapters/blob/04e69957a2bfc8093e2593186f7ebb2e71f88ec9/docs/loading.md#saving-and-loading-adapter-compositions)
```python
model = AutoAdapterModel.from_pretrained("roberta-base")
model.add_adapter("a", config=SeqBnConfig())
model.add_adapter("b", …
```
=> Allow saving, loading and pushing adapter compositions together

src/adapters/composition.py, src/adapters/configuration/model_adapters_config.py, src/adapters/loading.py, src/adapters/methods/bottleneck.py, src/adapters/model_mixin.py, tests/test_adapter_fusion_common.py
Resolves #316.
This PR implements the option to specify a custom name for an added AdapterFusion layer.
The name can be specified when adding a fusion layer like this:
```python
model.add_adapter_fusion(["adapter1", "adapter2"], name="custom_name_fusion")
```
Afterwards, to address the custom-name fusion, specify the name in the `Fuse` block. E.g. for activation:
```python
model.set_active_adapters(Fuse("adapter1", "adapter2", name="custom_name_fusion"))
```
Some fusion-specific methods can either take the named `Fuse` block or directly the fusion name:
```python
model.save_adapter_fusion("./checkpoint_dir", Fuse("adapter1", "adapter2", name="custom_name_fusion"))
model.delete_adapter_fusion(Fuse("adapter1", "adapter2", name="custom_name_fusion"))
```
=> Custom names for AdapterFusion layers

src/adapters/methods/reft.py, tests/methods/base.py, tests/methods/test_compacter.py, tests/methods/test_prefix_tuning.py, tests/methods/test_reft.py
Resolves #772.
Provides the following fixes for the ReFT implementation:
- support cases where seq_len < prefix/ suffix position (fixes issues with seq generation)
- ensure orthogonal projection is always initialized with float32 (as half precision is not supported)
=> ReFT generate & orthogonal fixes

README.md, docs/installation.md, setup.py, src/adapters/loading.py, src/adapters/model_mixin.py, src/adapters/trainer.py, tests/composition/test_parallel.py, tests/extended/test_adapter_trainer_ext.py, tests/methods/base.py, tests/test_adapter_conversion.py, tests/test_adapter_embeddings.py, tests/test_adapter_fusion_common.py, tests/test_adapter_heads.py, tests/test_adapter_hub.py, tests/test_adapter_trainer.py
Changes in this PR:
- set minimum supported Python version to 3.9 (following recent Transformers upgrade)
- reduce number of warnings in tests
- add `ignore_cleanup_errors=True` in full model loading tests to allow running on Windows
- minor fixes in Readme
=> Readme & test fixes

src/adapters/models/bart/adapter_model.py, src/adapters/models/bert/adapter_model.py, src/adapters/models/bert_generation/adapter_model.py, src/adapters/models/distilbert/adapter_model.py, src/adapters/models/electra/adapter_model.py, src/adapters/models/gpt2/adapter_model.py, src/adapters/models/gptj/adapter_model.py, src/adapters/models/llama/adapter_model.py, src/adapters/models/mbart/adapter_model.py, src/adapters/models/mistral/adapter_model.py, src/adapters/models/mt5/adapter_model.py, src/adapters/models/plbart/adapter_model.py, src/adapters/models/roberta/adapter_model.py, src/adapters/models/t5/adapter_model.py, src/adapters/models/whisper/adapter_model.py, src/adapters/models/xlm_roberta/adapter_model.py, src/adapters/models/xmod/adapter_model.py
Fixes the following warning for all AdapterModels:
```
LlamaAdapterModel has generative capabilities, as `prepare_inputs_for_generation` is explicitly overwritten. However, it doesn't directly inherit from `GenerationMixin`. From 👉v4.50👈 onwards, `PreTrainedModel` will NOT inherit from `GenerationMixin`, and this model will lose the ability to call `generate` and other related functions.
```
=> Fix GenerationMixin warning for AdapterModel classes

src/adapters/methods/prefix_tuning.py, tests/test_misc/test_adapter_composition.py
> Please refer to #794.  
In `BatchSplit.compose_single`, slicing for `BatchSplit` is not considered when `slice.start` exceeds the input batch size.  
If the last `batch_size` in `BatchSplit.batch_sizes` is `0`, the `start` and `stop` values of `state.idx_slice` are equal to the input batch size. As a result, the input prefix keys and values cannot be sliced into an empty tensor.
Useful for #792
=> Fix `BatchSplit` for `PrefixTuning`

src/adapters/context.py, src/adapters/heads/model_mixin.py, src/adapters/model_mixin.py, src/adapters/models/albert/adapter_model.py, src/adapters/models/bart/adapter_model.py, src/adapters/models/beit/adapter_model.py, src/adapters/models/bert/adapter_model.py, src/adapters/models/bert_generation/adapter_model.py, src/adapters/models/clip/adapter_model.py, src/adapters/models/deberta/adapter_model.py, src/adapters/models/deberta_v2/adapter_model.py, src/adapters/models/distilbert/adapter_model.py, src/adapters/models/electra/adapter_model.py, src/adapters/models/gpt2/adapter_model.py, src/adapters/models/gptj/adapter_model.py, src/adapters/models/llama/adapter_model.py, src/adapters/models/mbart/adapter_model.py, src/adapters/models/mistral/adapter_model.py, src/adapters/models/mt5/adapter_model.py, src/adapters/models/plbart/adapter_model.py, src/adapters/models/roberta/adapter_model.py, src/adapters/models/t5/adapter_model.py, src/adapters/models/vit/adapter_model.py, src/adapters/models/whisper/adapter_model.py, src/adapters/models/xlm_roberta/adapter_model.py, src/adapters/models/xmod/adapter_model.py, src/adapters/wrappers/model.py
This PR adapts the ForwardContext to be applied to the full model (including head) forward pass. The original base model forward wrapper is now moved to `wrap_base` to make sure no second ForwardContext is created for a single forward pass.
This enables passing custom args that are defined in the ForwardContext definition to the top-level model call, as discussed in #783, e.g.:
```python
model = AutoModelForCausalLM.from_pretrained(model_name)
adapters.init(model)
tokenizer = AutoTokenizer.from_pretrained(model_name)
inputs = tokenizer(["This is a test text"], return_tensors="pt")
ForwardContext.context_args.add("task_ids")
output = model(**inputs, task_ids=["id_0", "id_1"])
```
In the example above, the forward context will automatically add the passed context args as attributes, ie. …
=> Wrap ForwardContext around full model forward

src/adapters/wrappers/model.py, tests/test_methods/test_on_custom_interface.py
This PR introduces a validation for the values specified in the adapter interfaces. We now check that the layers specified actually exist and if not, we provide a detailed error to the user so that they know what went wrong.
Before this PR, when users specify layers in the adapter interfaces that don't exist in the model, there was no error thrown. This left users unaware that their specified values were invalid.
=> Adapter Interface: Validate Values

setup.py, src/adapters/__init__.py, src/adapters/head_utils.py, src/adapters/heads/model_mixin.py, src/adapters/models/beit/modeling_beit.py, src/adapters/models/vit/modeling_vit.py, tests/test_models/base.py
Changes required for compatibility to v4.50:
- Refactor automatic static to flex head conversion on full model loading
- Update Beit and Vit attention implementations
- Skip generation tests for AdapterModel classes
=> Upgrade Transformers to v4.50.x

examples/pytorch/dependency-parsing/utils_udp.py, examples/pytorch/question-answering/trainer_qa.py, examples/pytorch/question-answering/trainer_seq2seq_qa.py, setup.py, src/adapters/methods/lora.py, src/adapters/methods/modeling.py, src/adapters/methods/reft.py, tests/test_models/test_clip_model.py
This PR upgrades transformers to v4.51.x.
Required changes in the adapters code base:
- Properly skip sdpa inference tests for CLIP
- Remove deprecated tpu availability method from example scripts
- Update weight initialization for BertFusion
- Avoid tensor allocation on meta device for LoRA and REFT parametrization
=> Upgrade transformers to 4.51.3
